apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: people
spec:
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          args: ["--bind_ip_all"]
          ports: [{ containerPort: 27017 }]
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: people
spec:
  selector: { app: mongo }
  ports: [{ port: 27017, targetPort: 27017 }]
